# Generated by Django 3.1.6 on 2021-02-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(db_column='OrganizationID', primary_key=True, serialize=False)),
                ('organization_name', models.CharField(db_column='OrganizationName', max_length=255)),
                ('city', models.CharField(blank=True, db_column='City', max_length=255, null=True)),
                ('revenue', models.IntegerField(blank=True, db_column='Revenue', null=True)),
                ('it_employee_scale', models.IntegerField(blank=True, db_column='ITEmployeeScale', null=True)),
                ('employee_scale', models.IntegerField(blank=True, db_column='EmployeeScale', null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=255, null=True)),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
            ],
            options={
                'db_table': 'Organization',
                'managed': False,
            },
        ),
    ]
