# Generated by Django 3.1.6 on 2021-02-20 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_city_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
