# Generated by Django 3.1.6 on 2021-04-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measuretype',
            fields=[
                ('measure_type_id', models.AutoField(db_column='MeasureTypeID', primary_key=True, serialize=False)),
                ('measure_name', models.CharField(db_column='MeasureName', max_length=128)),
                ('modify_time', models.TextField(blank=True, db_column='ModifyTime', null=True)),
                ('reduced_vulnerability_defult', models.FloatField(blank=True, db_column='ReducedVulnerabilityDefault', null=True)),
                ('reduced_l1_rate_default', models.FloatField(blank=True, db_column='ReducedL1RateDefault', null=True)),
                ('reduced_l2_rate_default', models.FloatField(blank=True, db_column='ReducedL2RateDefault', null=True)),
                ('is_valid', models.BooleanField(blank=True, db_column='isValid', null=True)),
            ],
            options={
                'db_table': 'MeasureType',
                'managed': False,
            },
        ),
    ]
