# Generated by Django 3.1.6 on 2021-02-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0003_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'managed': False},
        ),
    ]
