# Generated by Django 3.1.6 on 2021-02-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0004_auto_20210219_1410'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sector',
            table='Sector',
        ),
    ]
