# Generated by Django 3.1.6 on 2021-02-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0005_auto_20210219_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'managed': True},
        ),
    ]
