# Generated by Django 3.1.6 on 2021-02-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0006_auto_20210219_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'managed': False},
        ),
    ]
