# Generated by Django 3.1.6 on 2021-03-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attackinformation',
            fields=[
                ('attack_id', models.CharField(db_column='AttackID', max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_column='UserID')),
                ('timetorepair_without', models.IntegerField(blank=True, db_column='TimetoRepair_without', null=True)),
                ('timetodetect_without', models.IntegerField(blank=True, db_column='TimetoDetect_without', null=True)),
                ('costofequipmentreplacement', models.TextField(blank=True, db_column='CostofEquipmentReplacement', null=True)),
                ('costofrepair', models.TextField(blank=True, db_column='CostofRepair', null=True)),
                ('corporate_income_loss', models.TextField(blank=True, db_column='CorporateIncomeLoss', null=True)),
                ('organization_productive_loss', models.TextField(blank=True, db_column='OrganizationProductiveLoss', null=True)),
                ('sla_loss', models.TextField(blank=True, db_column='SLALoss', null=True)),
                ('indirect_loss', models.TextField(blank=True, db_column='IndirectLoss', null=True)),
                ('loss_duration', models.TextField(blank=True, db_column='LossDuration', null=True)),
                ('incident_effect', models.TextField(blank=True, db_column='IncidentEffect', null=True)),
                ('loss_property', models.TextField(blank=True, db_column='LossProperty', null=True)),
                ('attacker_infrastructure', models.TextField(blank=True, db_column='AttackerInfrastructure', null=True)),
                ('threat_actor_type', models.TextField(blank=True, db_column='ThreatActorType', null=True)),
                ('attacker_tool', models.TextField(blank=True, db_column='AttackerTool', null=True)),
                ('malware_type', models.TextField(blank=True, db_column='MalwareType', null=True)),
                ('malicious_e_mail', models.TextField(blank=True, db_column='MaliciousE-mail', null=True)),
                ('ip_watchlist', models.TextField(blank=True, db_column='IPWatchlist', null=True)),
                ('file_hash_watchlist', models.TextField(blank=True, db_column='FileHashWatchlist', null=True)),
                ('domain_watchlist', models.TextField(blank=True, db_column='DomainWatchlist', null=True)),
                ('url_watchlist', models.TextField(blank=True, db_column='URLWatchlist', null=True)),
                ('host_characteristics', models.TextField(blank=True, db_column='HostCharacteristics', null=True)),
                ('system_type', models.TextField(blank=True, db_column='SystemType', null=True)),
                ('asset_type', models.TextField(blank=True, db_column='AssetType', null=True)),
                ('discovery_method', models.TextField(blank=True, db_column='DiscoveryMethod', null=True)),
                ('l1', models.TextField(blank=True, db_column='L1', null=True)),
                ('l2', models.TextField(blank=True, db_column='L2', null=True)),
                ('l3', models.TextField(blank=True, db_column='L3', null=True)),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
                ('discount_rate', models.TextField(blank=True, db_column='DiscountRate', null=True)),
            ],
            options={
                'db_table': 'AttackInformation',
                'managed': False,
            },
        ),
    ]
