# Generated by Django 3.1.6 on 2021-03-24 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information_sharing', '0003_lossproperty_malwaretype_measuretype_securitycompromise_systemtype_threatactortype'),
        ('attack_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attackinformation2Assettype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_sharing.assettype')),
                ('attack_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attack_information.attackinformation')),
            ],
        ),
    ]
