# Generated by Django 3.1.6 on 2021-03-27 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information_sharing', '0004_auto_20210327_2105'),
        ('attack_information', '0002_attackinformation2assettype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attackinformation2Threatactortype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
                ('attack_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attack_information.attackinformation')),
                ('attacker_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_sharing.threatactortype')),
            ],
        ),
        migrations.CreateModel(
            name='Attackinformation2Systemtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
                ('attack_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attack_information.attackinformation')),
                ('system_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_sharing.systemtype')),
            ],
        ),
        migrations.CreateModel(
            name='Attackinformation2Malwaretype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
                ('attack_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attack_information.attackinformation')),
                ('malware_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_sharing.malwaretype')),
            ],
        ),
        migrations.CreateModel(
            name='Attackinformation2Lossproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
                ('attack_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attack_information.attackinformation')),
                ('loss_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_sharing.lossproperty')),
            ],
        ),
        migrations.CreateModel(
            name='Attackinformation2Incidenteffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
                ('attack_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attack_information.attackinformation')),
                ('incident_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_sharing.incidenteffect')),
            ],
        ),
        migrations.CreateModel(
            name='Attackinformation2Attackertool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
                ('attack_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attack_information.attackinformation')),
                ('attacker_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_sharing.attackertool')),
            ],
        ),
        migrations.CreateModel(
            name='Attackinformation2Attackerinfrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
                ('attack_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attack_information.attackinformation')),
                ('attacker_infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_sharing.attackerinfrastructure')),
            ],
        ),
    ]
