# Generated by Django 3.1.6 on 2021-03-27 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information_sharing', '0005_discoverymethod'),
        ('attack_information', '0003_attackinformation2attackerinfrastructure_attackinformation2attackertool_attackinformation2incidentef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attackinformation2Discoverymethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
                ('attack_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attack_information.attackinformation')),
                ('discovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_sharing.discoverymethod')),
            ],
        ),
    ]
