# Generated by Django 3.1.6 on 2021-03-27 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attack_information', '0004_attackinformation2discoverymethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attackinformation2threatactortype',
            old_name='attacker_tool',
            new_name='threat_actor_type',
        ),
    ]
