# Generated by Django 3.1.6 on 2021-04-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('measure_id', models.AutoField(db_column='MeasureID', primary_key=True, serialize=False)),
                ('measure_description', models.TextField(blank=True, db_column='MeasureDescription', null=True)),
                ('rosi', models.TextField(blank=True, db_column='ROSI', null=True)),
                ('npv', models.TextField(blank=True, db_column='NPV', null=True)),
                ('time_period', models.IntegerField(blank=True, db_column='TimePeriod', null=True)),
                ('initial_cost', models.TextField(blank=True, db_column='InitialCost', null=True)),
                ('annual_upgrade', models.TextField(blank=True, db_column='AnnualUpgrade', null=True)),
                ('annual_maintenance', models.TextField(blank=True, db_column='AnnualMaintenance', null=True)),
                ('total_cost', models.TextField(blank=True, db_column='TotalCost', null=True)),
                ('reduced_vulnerability', models.TextField(blank=True, db_column='ReducedVulnerability', null=True)),
                ('insurance_amount', models.TextField(blank=True, db_column='InsuranceAmount', null=True)),
                ('times_of_attack', models.IntegerField(blank=True, db_column='TimesofAttack', null=True)),
                ('times_of_success_attack', models.IntegerField(blank=True, db_column='TimesofSuccessAttack', null=True)),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
                ('vulnerability_without_measure', models.TextField(blank=True, db_column='VulnerabilityWithoutMeasure', null=True)),
                ('reduced_l1_rate', models.TextField(blank=True, db_column='ReducedL1Rate', null=True)),
                ('reduced_l2_rate', models.TextField(blank=True, db_column='ReducedL2Rate', null=True)),
                ('discount_rate', models.TextField(blank=True, db_column='DiscountRate', null=True)),
            ],
            options={
                'db_table': 'Measures',
                'managed': False,
            },
        ),
    ]
