# Generated by Django 3.1.6 on 2021-02-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assettype',
            fields=[
                ('asset_type_id', models.AutoField(db_column='AssetTypeID', primary_key=True, serialize=False)),
                ('asset_type', models.CharField(db_column='AssetType', max_length=128)),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
                ('is_valid', models.BooleanField(blank=True, db_column='isValid', null=True)),
            ],
            options={
                'verbose_name': 'asset type',
                'verbose_name_plural': 'asset types',
                'db_table': 'AssetType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attackerinfrastructure',
            fields=[
                ('attacker_infrastructure_id', models.AutoField(db_column='AttackerInfrastructureID', primary_key=True, serialize=False)),
                ('attacker_infrastructure', models.CharField(db_column='AttackerInfrastructure', max_length=128)),
                ('modify_time', models.TextField(blank=True, db_column='ModifyTime', null=True)),
                ('is_valid', models.TextField(blank=True, db_column='isValid', null=True)),
            ],
            options={
                'db_table': 'AttackerInfrastructure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attackertool',
            fields=[
                ('attacker_tool_id', models.AutoField(db_column='AttackerToolID', primary_key=True, serialize=False)),
                ('attacker_tool', models.CharField(db_column='AttackerTool', max_length=128)),
                ('modify_time', models.TextField(blank=True, db_column='ModifyTime', null=True)),
                ('is_valid', models.TextField(blank=True, db_column='isValid', null=True)),
            ],
            options={
                'db_table': 'AttackerTool',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Impactrating',
            fields=[
                ('impact_rating_id', models.AutoField(db_column='ImpactRatingID', primary_key=True, serialize=False)),
                ('impact_rating', models.CharField(db_column='ImpactRating', max_length=128)),
                ('modify_time', models.TextField(blank=True, db_column='ModifyTime', null=True)),
            ],
            options={
                'db_table': 'ImpactRating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidentcategory',
            fields=[
                ('incident_category_id', models.AutoField(db_column='IncidentCategoryID', primary_key=True, serialize=False)),
                ('incident_category', models.CharField(db_column='IncidentCategory', max_length=128)),
                ('modify_time', models.TextField(blank=True, db_column='ModifyTime', null=True)),
            ],
            options={
                'db_table': 'IncidentCategory',
                'managed': False,
            },
        ),
    ]
