# Generated by Django 3.1.6 on 2021-02-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_sharing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidenteffect',
            fields=[
                ('incident_effect_id', models.AutoField(db_column='IncidentEffectID', primary_key=True, serialize=False)),
                ('incident_effect', models.CharField(db_column='IncidentEffect', max_length=128)),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
                ('is_valid', models.BooleanField(blank=True, db_column='isValid', null=True)),
            ],
            options={
                'verbose_name': 'Incident Effect',
                'verbose_name_plural': 'Incident Effect',
                'db_table': 'IncidentEffect',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='attackerinfrastructure',
            options={'managed': False, 'verbose_name': 'Attacker Infrastructure', 'verbose_name_plural': 'Attacker Infrastructures'},
        ),
        migrations.AlterModelOptions(
            name='attackertool',
            options={'managed': False, 'verbose_name': 'Attacker Tool', 'verbose_name_plural': 'Attacker Tools'},
        ),
        migrations.AlterModelOptions(
            name='impactrating',
            options={'managed': False, 'verbose_name': 'Impact Rating', 'verbose_name_plural': 'Impact Ratings'},
        ),
        migrations.AlterModelOptions(
            name='incidentcategory',
            options={'managed': False, 'verbose_name': 'IncidentCategory', 'verbose_name_plural': 'Incident Categories'},
        ),
    ]
