# Generated by Django 3.1.6 on 2021-03-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information_sharing', '0003_lossproperty_malwaretype_measuretype_securitycompromise_systemtype_threatactortype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidenteffect',
            options={'managed': False, 'verbose_name': 'Incident Effect', 'verbose_name_plural': 'Incident Effects'},
        ),
        migrations.AlterModelOptions(
            name='lossproperty',
            options={'managed': False, 'verbose_name': 'Loss Property', 'verbose_name_plural': 'Loss Properties'},
        ),
        migrations.AlterModelOptions(
            name='malwaretype',
            options={'managed': False, 'verbose_name': 'Malware Type', 'verbose_name_plural': 'Malware Types'},
        ),
        migrations.AlterModelOptions(
            name='measuretype',
            options={'managed': False, 'verbose_name': 'Measure Type', 'verbose_name_plural': 'Measure Types'},
        ),
        migrations.AlterModelOptions(
            name='systemtype',
            options={'managed': False, 'verbose_name': 'System Type', 'verbose_name_plural': 'System Types'},
        ),
        migrations.AlterModelOptions(
            name='threatactortype',
            options={'managed': False, 'verbose_name': 'Threat Actor Type', 'verbose_name_plural': 'Threat Actor Types'},
        ),
    ]
