# Generated by Django 3.1.6 on 2021-03-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_sharing', '0004_auto_20210327_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discoverymethod',
            fields=[
                ('discovery_method_id', models.AutoField(db_column='DiscoveryMethodID', primary_key=True, serialize=False)),
                ('discovery_method', models.CharField(db_column='DiscoveryMethod', max_length=128)),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
            ],
            options={
                'verbose_name': 'Discovery Method',
                'verbose_name_plural': 'Discovery Methods',
                'db_table': 'DiscoveryMethod',
                'managed': False,
            },
        ),
    ]
