# Generated by Django 3.1.6 on 2021-04-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_sharing', '0005_discoverymethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lossduration',
            fields=[
                ('loss_duration_id', models.AutoField(db_column='LossDurationID', primary_key=True, serialize=False)),
                ('loss_duration', models.CharField(db_column='LossDuration', max_length=128)),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
            ],
            options={
                'verbose_name': 'Loss Duration',
                'verbose_name_plural': 'Loss Duration',
                'db_table': 'LossDuration',
                'managed': False,
            },
        ),
    ]
