# Generated by Django 3.1.6 on 2021-04-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information_sharing', '0006_lossduration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measuretype',
        ),
    ]
