# Generated by Django 3.1.6 on 2021-03-24 20:54

import attack_features.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attackfeatures',
            fields=[
                ('attack_id', models.CharField(db_column='AttackID', max_length=255, primary_key=True, serialize=False)),
                ('start_time_stamp', models.DateTimeField(blank=True, db_column='StartTimeStamp', null=True)),
                ('end_time_stamp', models.DateTimeField(blank=True, db_column='EndTimeStamp', null=True)),
                ('duration', models.IntegerField(blank=True, db_column='Duration', null=True)),
                ('nr_of_ip_packets', models.IntegerField(blank=True, db_column='NrOfIPpackets', null=True)),
                ('attack_size_in_bytes', models.IntegerField(blank=True, db_column='AttackSizeInBytes', null=True)),
                ('nr_of_src_ips', models.IntegerField(blank=True, db_column='NrOfSrcIps', null=True)),
                ('nr_of_dst_ips', models.IntegerField(blank=True, db_column='NrOfDstIps', null=True)),
                ('top_5_src_ip', models.TextField(blank=True, db_column='Top5SrcIP', null=True)),
                ('nr_of_src_port', models.IntegerField(blank=True, db_column='NrOfSrcPort', null=True)),
                ('nr_of_ds_port', models.IntegerField(blank=True, db_column='NrOfDsPort', null=True)),
                ('top_20_des_port', models.TextField(blank=True, db_column='Top20DesPort', null=True)),
                ('top_http_verb', models.TextField(blank=True, db_column='TopHttpVerb', null=True)),
                ('top_http_endpoint', models.TextField(blank=True, db_column='TopHttpEndpoint', null=True)),
                ('top_browser_os', models.TextField(blank=True, db_column='TopBrowserOS', null=True)),
                ('top_device', models.TextField(blank=True, db_column='TopDevice', null=True)),
                ('modify_time', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
            ],
            options={
                'db_table': 'AttackFeatures',
                'managed': False,
            },
        ),
    ]
