# Generated by Django 3.1.6 on 2021-03-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('userfirstname', models.CharField(db_column='UserFirstName', max_length=255)),
                ('userlastname', models.CharField(db_column='UserLastName', max_length=255)),
                ('useremail', models.CharField(db_column='UserEmail', max_length=255)),
                ('userscale', models.IntegerField(blank=True, db_column='UserScale', null=True)),
                ('modifytime', models.DateTimeField(auto_now=True, db_column='ModifyTime', null=True)),
            ],
            options={
                'db_table': 'UserInfo',
                'managed': False,
            },
        ),
    ]
