# Generated by Django 3.1.6 on 2021-02-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityid', models.IntegerField(db_column='CityID')),
                ('cityname', models.CharField(db_column='CityName', max_length=128)),
                ('countrycode', models.IntegerField(db_column='CountryCode', max_length=128)),
                ('countryid', models.IntegerField(blank=True, db_column='CountryID', null=True)),
            ],
            options={
                'db_table': 'City',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryid', models.IntegerField(db_column='CountryID')),
                ('countryname', models.CharField(db_column='CountryName', max_length=128)),
                ('countrycode', models.CharField(db_column='CountryCode', max_length=128)),
            ],
            options={
                'db_table': 'Country',
                'managed': False,
            },
        ),
    ]
